### PR TITLE
Suggested fix for #160

### LINKED ISSUE #160: maxUploadRows in BasicUploadManager ignored
The `maxUploadRows` field is set but never used to ensure that table uploads don't exceed some arbitrary size.  This is helpful to prevent excessive load on databases.

### PR DESCRIPTION
**Pull request by at88mph**
Fixes #160 
Add Upload limits for byte size, row count, and column count.

### CODE REVIEW

File: cadc-tap-server/src/main/java/ca/nrc/cadc/tap/upload/JDOMVOTableParser.java [hunk 1]
```diff
@@ -99,42 +98,78 @@ public class JDOMVOTableParser implements VOTableParser
...
 
     private void init()
         throws IOException
     {
         if (votable == null)
         {
+            verifyUploadTable();
             VOTableReader r = new VOTableReader();
-            // TODO: wrap a ByteCountInputStream here to limit input data volume
             VOTableDocument doc = r.read(upload.uri.toURL().openStream());
```
Comment (pdowler) [inline cadc-tap-server/src/main/java/ca/nrc/cadc/tap/upload/JDOMVOTableParser.java:119]: this existing code will read the votable doc for a second time (1st in verify above), which is wasteful and would make it only work  on a re-readable location. That would make it hard to receive an inline table and send it directly to the database.

Can you change verifyUploadTable to return the VOTableDocument (when successful) so it can be kept here?

File: cadc-tap-server/src/main/java/ca/nrc/cadc/tap/upload/JDOMVOTableParser.java [hunk 2]
```diff
@@ -99,42 +98,78 @@ public class JDOMVOTableParser implements VOTableParser
...
+            }
+        }
+    }
+
+    /**
+     * Ensure the Upload table conforms to specified limitations, if any.  This will only read through the file if
+     * the Upload table file falls into the acceptable size first.
+     * @throws IOException  If any of the limitations are exceeded.
+     */
+    void verifyUploadTable() throws IOException {
```
Comment (pdowler) [inline cadc-tap-server/src/main/java/ca/nrc/cadc/tap/upload/JDOMVOTableParser.java:134]: the ByteCountInputStream throws a ByteLimitExceededException (runtime)

I think IOException should only be used for a real IO failure; here, exceeding limits needs to result in a 4xx failure...

IllegalArgumentException -> 400 is minimally correct for exceeding the limits and should prevent the caller from retrying.

File: cadc-tap-server/src/main/java/ca/nrc/cadc/tap/upload/UploadLimits.java [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+ *                                       <http://www.gnu.org/licenses/>.
+ *
+ *
+ ************************************************************************
+ */
+
+package ca.nrc.cadc.tap.upload;
+
+public class UploadLimits {
+    final Long byteLimit;
```
Comment (pdowler) [inline cadc-tap-server/src/main/java/ca/nrc/cadc/tap/upload/UploadLimits.java:72]: Since byteLimit is mandatory to do anything safe and useful, I would make it a `long` so it cannot be null. And sanity check in the ctor that `byteLimit > 0`. 

General style: we have been using ctor args to tell developersd which things and mandatory and public fields (not final) for those that can be null. It's a little more tedious than using a convenient 3-arg ctor but it seems to be less surprising and less fragile over the long term. So `UploadLimits(long byteLimit)` and make `rowLimit` and `columnLimit` non-final and public so they can be assigned or not.

This also simplifies other code.

File: cadc-tap-server/src/main/java/ca/nrc/cadc/tap/upload/JDOMVOTableParser.java [hunk 4]
```diff
@@ -99,42 +98,78 @@ public class JDOMVOTableParser implements VOTableParser
     
     protected String tableName;
     protected VOTableTable votable;
+    protected UploadLimits uploadLimits;
 
     public JDOMVOTableParser() { }
```
Comment (pdowler) [inline cadc-tap-server/src/main/java/ca/nrc/cadc/tap/upload/JDOMVOTableParser.java:103]: Having an `UploadLimits` object is operationally required so I would make it a a ctor arg and check for null. That also simplifies `verifyUploadTable` and forces it to always check.

File: cadc-tap-server/src/main/java/ca/nrc/cadc/tap/BasicUploadManager.java [hunk 5]
```diff
@@ -121,9 +119,9 @@ public class BasicUploadManager implements UploadManager
     protected DateFormat dateFormat;
 
     /**
-     * Maximum number of rows allowed in the UPLOAD VOTable.
+     * Limitations on the UPLOAD VOTable.
      */
-    protected int maxUploadRows;
+    protected UploadLimits uploadLimits;
```
Comment (pdowler) [inline cadc-tap-server/src/main/java/ca/nrc/cadc/tap/BasicUploadManager.java:124]: I would assign a conservative default limit of `new UploadLimit(...)` with byteLimit of a few MiB, maybe even 1 (1024*1024) so a service is nominally usable without subclassing and remembering to do something here. 

Then don't allow `null` in the ctor.

**Comment by at88mph** [comment]
Null constructor arguments throw an `IllegalStateException`.  Limit exceeding throws an `IllegalArgumentException`.

**Review by pdowler — APPROVED** [review]
